### ISSUE TITLE
SE for Nhat.resid?

### ISSUE THREAD

**Issue by scrogster** [eradicate-dev/eradicate#3]
For consistency, is it possible toinclude a standard error for Nresid as well as Nhat in the removal models?
`#scrathpad for eradication phase
library(eradicate)
library(sf)
library(raster)

region<- read_sf(system.file("extdata", "shape/san_nic_region.shp", package="eradicate"))
habitat<- raster(system.file("extdata", "san_nic_habitat.tif", package="eradicate"))

#rows = traps, cols = sessions
rem<- san_nic_rem$rem
#plot cumulative removals across all sites
plot(cumsum(colSums(rem)))

y1<- san_nic_rem$y1 # detections from additional monitoring
plot(cumsum(colSums(y1)))

mtraps<- san_nic_rem$cells

nights<- san_nic_rem$nights

traps<- san_nic_rem$traps

habvals<- raster::extract(habitat, traps, buffer=500)
pgrass<- sapply(habvals, function(x) mean(x, na.rm=T))
site.data<- cbind(traps, pgrass)

emf<-eFrameRM(rem, y1, mtraps, nights, type="removal", siteCovs = site.data)
r1<- remPoisM(~ pgrass,  ~ 1, data=emf, K=50)
calcN(r1)`

**Comment by dslramsey** [comment]
Not sure why I didn't include this, but its an easy fix.

**Comment by dslramsey** [comment]
OK have now fixed this as well as the glitch in the vignette

**Comment by scrogster** [comment]
Cool.
